services:
  php:
    image: php-image:v1
    restart: unless-stopped
    ports:
      - "4600:80"
    volumes:
      - /home/development/php-udemy/www:/var/www/html
    container_name: php-image
    depends_on:
      - db

  db:
    image: mariadb:lts-noble
    restart: unless-stopped
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: mariadb-container

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "4601:80"
    environment:
      PMA_HOST: db
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - db
